In [1]:

import pandas as pd
import numpy as np

from pathlib import Path
from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:

PROJECT_DIR = Path(
    "/Users/monicachaganti/Desktop/Ph.D/PROJECTS/brca_metabric"
)

DATA_FILE = (
    PROJECT_DIR
    / "processed_data"
    / "metabric_survival_cohort.csv"
)

df = pd.read_csv(DATA_FILE)

print("Dataset shape:", df.shape)

display(df.head())

Dataset shape: (1981, 37)

,PATIENT_ID,LYMPH_NODES_EXAMINED_POSITIVE,NPI,CELLULARITY,CHEMOTHERAPY,COHORT,ER_IHC,HER2_SNP6,HORMONE_THERAPY,INFERRED_MENOPAUSAL_STATE,SEX,INTCLUST,AGE_AT_DIAGNOSIS,OS_MONTHS,OS_STATUS,CLAUDIN_SUBTYPE,THREEGENE,VITAL_STATUS,LATERALITY,RADIO_THERAPY,HISTOLOGICAL_SUBTYPE,BREAST_SURGERY,RFS_MONTHS,RFS_STATUS,SAMPLE_ID,CANCER_TYPE,CANCER_TYPE_DETAILED,ER_STATUS,HER2_STATUS,GRADE,ONCOTREE_CODE,PR_STATUS,SAMPLE_TYPE,TUMOR_SIZE,TUMOR_STAGE,TMB_NONSYNONYMOUS,EVENT
0,MB-0000,10.0,6.044,NaN,NO,1.0,Positve,NEUTRAL,YES,Post,Female,4ER+,75.65,140.500000,0:LIVING,claudin-low,ER-/HER2-,Living,Right,YES,Ductal/NST,MASTECTOMY,140.500000,0:Not Recurred,MB-0000,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,3.0,IDC,Negative,Primary,22.0,2.0,0.000000,0
1,MB-0002,0.0,4.020,High,NO,1.0,Positve,NEUTRAL,YES,Pre,Female,4ER+,43.19,84.633333,0:LIVING,LumA,ER+/HER2- High Prolif,Living,Right,YES,Ductal/NST,BREAST CONSERVING,84.633333,0:Not Recurred,MB-0002,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,3.0,IDC,Positive,Primary,10.0,1.0,2.615035,0
2,MB-0005,1.0,4.030,High,YES,1.0,Positve,NEUTRAL,YES,Pre,Female,3,48.87,163.700000,1:DECEASED,LumB,NaN,Died of Disease,Right,NO,Ductal/NST,MASTECTOMY,153.300000,1:Recurred,MB-0005,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,2.0,IDC,Positive,Primary,15.0,2.0,2.615035,1
3,MB-0006,3.0,4.050,Moderate,YES,1.0,Positve,NEUTRAL,YES,Pre,Female,9,47.68,164.933333,0:LIVING,LumB,NaN,Living,Right,YES,Mixed,MASTECTOMY,164.933333,0:Not Recurred,MB-0006,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Positive,Negative,2.0,MDLC,Positive,Primary,25.0,2.0,1.307518,0
4,MB-0008,8.0,6.080,High,YES,1.0,Positve,NEUTRAL,YES,Post,Female,9,76.97,41.366667,1:DECEASED,LumB,ER+/HER2- High Prolif,Died of Disease,Right,YES,Mixed,MASTECTOMY,18.800000,1:Recurred,MB-0008,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Positive,Negative,3.0,MDLC,Positive,Primary,40.0,2.0,2.615035,1

In [5]:

column_summary = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Missing_Count": df.isna().sum().values,
    "Missing_Percentage": (
        df.isna().mean().values * 100
    ),
    "Unique_Values": df.nunique(dropna=True).values
})

display(
    column_summary.sort_values(
        by="Missing_Percentage",
        ascending=False
    ).round(2)
)

,Column,Data_Type,Missing_Count,Missing_Percentage,Unique_Values
34,TUMOR_STAGE,float64,515,26.00,5
16,THREEGENE,object,217,10.95,4
18,LATERALITY,object,111,5.60,2
29,GRADE,float64,88,4.44,3
1,LYMPH_NODES_EXAMINED_POSITIVE,float64,76,3.84,31
3,CELLULARITY,object,64,3.23,3
20,HISTOLOGICAL_SUBTYPE,object,44,2.22,8
6,ER_IHC,object,43,2.17,2
21,BREAST_SURGERY,object,26,1.31,2
33,TUMOR_SIZE,float64,26,1.31,112
15,CLAUDIN_SUBTYPE,object,1,0.05,7
23,RFS_STATUS,object,1,0.05,2
19,RADIO_THERAPY,object,1,0.05,2
17,VITAL_STATUS,object,1,0.05,3
28,HER2_STATUS,object,1,0.05,2
31,PR_STATUS,object,1,0.05,2
11,INTCLUST,object,1,0.05,11
9,INFERRED_MENOPAUSAL_STATE,object,1,0.05,2
8,HORMONE_THERAPY,object,1,0.05,2
7,HER2_SNP6,object,1,0.05,4
4,CHEMOTHERAPY,object,1,0.05,2
2,NPI,float64,1,0.05,320
27,ER_STATUS,object,0,0.00,2
35,TMB_NONSYNONYMOUS,float64,0,0.00,31
30,ONCOTREE_CODE,object,0,0.00,8
32,SAMPLE_TYPE,object,0,0.00,1
0,PATIENT_ID,object,0,0.00,1981
26,CANCER_TYPE_DETAILED,object,0,0.00,8
25,CANCER_TYPE,object,0,0.00,1
24,SAMPLE_ID,object,0,0.00,1981
22,RFS_MONTHS,float64,0,0.00,1716
14,OS_STATUS,object,0,0.00,2
13,OS_MONTHS,float64,0,0.00,1743
12,AGE_AT_DIAGNOSIS,float64,0,0.00,1624
10,SEX,object,0,0.00,1
5,COHORT,float64,0,0.00,5
36,EVENT,int64,0,0.00,2

In [7]:

print("Patients:", len(df))

print("\nEvent distribution:")
print(df["EVENT"].value_counts())

print("\nSurvival time summary:")
display(df["OS_MONTHS"].describe())

print("\nMissing outcome values:")
print(df[["OS_MONTHS", "EVENT"]].isna().sum())

Patients: 1981

Event distribution:
EVENT
1    1144
0     837
Name: count, dtype: int64

Survival time summary:

count    1981.000000
mean      125.244271
std        76.111772
min         0.000000
25%        60.866667
50%       116.466667
75%       185.133333
max       355.200000
Name: OS_MONTHS, dtype: float64

Missing outcome values:
OS_MONTHS    0
EVENT        0
dtype: int64

In [9]:

train_df, test_df = train_test_split(
    df,
    test_size=0.20,
    random_state=42,
    stratify=df["EVENT"]
)

train_df = train_df.copy()

test_df = test_df.copy()

print("Training patients:", len(train_df))

print("Test patients:", len(test_df))

print("\nTraining event distribution:")
print(train_df["EVENT"].value_counts())

print("\nTest event distribution:")
print(test_df["EVENT"].value_counts())

Training patients: 1584
Test patients: 397

Training event distribution:
EVENT
1    915
0    669
Name: count, dtype: int64

Test event distribution:
EVENT
1    229
0    168
Name: count, dtype: int64

In [13]:

print("Training duplicate rows:", train_df.duplicated().sum())

print("Test duplicate rows:", test_df.duplicated().sum())

print(
    "Overlapping row indices:",
    len(set(train_df.index) & set(test_df.index))
)

assert set(train_df.index).isdisjoint(set(test_df.index))

print("Train-test row separation verified!")

Training duplicate rows: 0
Test duplicate rows: 0
Overlapping row indices: 0
Train-test row separation verified!

In [15]:

column_summary = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Missing_Count": df.isna().sum().values,
    "Missing_Percentage": df.isna().mean().values * 100,
    "Unique_Values": df.nunique(dropna=True).values
})

display(
    column_summary.sort_values(
        by="Missing_Percentage",
        ascending=False
    ).round(2)
)

print("\nPotential patient identifier columns:")

print([
    col for col in df.columns
    if "PATIENT" in col.upper()
    or "SAMPLE" in col.upper()
    or col.upper().endswith("_ID")
])

,Column,Data_Type,Missing_Count,Missing_Percentage,Unique_Values
34,TUMOR_STAGE,float64,515,26.00,5
16,THREEGENE,object,217,10.95,4
18,LATERALITY,object,111,5.60,2
29,GRADE,float64,88,4.44,3
1,LYMPH_NODES_EXAMINED_POSITIVE,float64,76,3.84,31
3,CELLULARITY,object,64,3.23,3
20,HISTOLOGICAL_SUBTYPE,object,44,2.22,8
6,ER_IHC,object,43,2.17,2
21,BREAST_SURGERY,object,26,1.31,2
33,TUMOR_SIZE,float64,26,1.31,112
15,CLAUDIN_SUBTYPE,object,1,0.05,7
23,RFS_STATUS,object,1,0.05,2
19,RADIO_THERAPY,object,1,0.05,2
17,VITAL_STATUS,object,1,0.05,3
28,HER2_STATUS,object,1,0.05,2
31,PR_STATUS,object,1,0.05,2
11,INTCLUST,object,1,0.05,11
9,INFERRED_MENOPAUSAL_STATE,object,1,0.05,2
8,HORMONE_THERAPY,object,1,0.05,2
7,HER2_SNP6,object,1,0.05,4
4,CHEMOTHERAPY,object,1,0.05,2
2,NPI,float64,1,0.05,320
27,ER_STATUS,object,0,0.00,2
35,TMB_NONSYNONYMOUS,float64,0,0.00,31
30,ONCOTREE_CODE,object,0,0.00,8
32,SAMPLE_TYPE,object,0,0.00,1
0,PATIENT_ID,object,0,0.00,1981
26,CANCER_TYPE_DETAILED,object,0,0.00,8
25,CANCER_TYPE,object,0,0.00,1
24,SAMPLE_ID,object,0,0.00,1981
22,RFS_MONTHS,float64,0,0.00,1716
14,OS_STATUS,object,0,0.00,2
13,OS_MONTHS,float64,0,0.00,1743
12,AGE_AT_DIAGNOSIS,float64,0,0.00,1624
10,SEX,object,0,0.00,1
5,COHORT,float64,0,0.00,5
36,EVENT,int64,0,0.00,2

Potential patient identifier columns:
['PATIENT_ID', 'SAMPLE_ID', 'SAMPLE_TYPE']

In [17]:

patient_id_column = "PATIENT_ID"

print(
    "Unique patients in full cohort:",
    df[patient_id_column].nunique()
)

print(
    "Patients appearing in both sets:",
    len(
        set(train_df[patient_id_column])
        & set(test_df[patient_id_column])
    )
)

assert set(train_df[patient_id_column]).isdisjoint(
    set(test_df[patient_id_column])
)

Unique patients in full cohort: 1981
Patients appearing in both sets: 0

In [19]:

display(
    pd.DataFrame({
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str).values,
        "Missing_Count": df.isna().sum().values,
        "Missing_Percentage": df.isna().mean().values * 100,
        "Unique_Values": df.nunique(dropna=True).values
    }).round(2)
)

,Column,Data_Type,Missing_Count,Missing_Percentage,Unique_Values
0,PATIENT_ID,object,0,0.00,1981
1,LYMPH_NODES_EXAMINED_POSITIVE,float64,76,3.84,31
2,NPI,float64,1,0.05,320
3,CELLULARITY,object,64,3.23,3
4,CHEMOTHERAPY,object,1,0.05,2
5,COHORT,float64,0,0.00,5
6,ER_IHC,object,43,2.17,2
7,HER2_SNP6,object,1,0.05,4
8,HORMONE_THERAPY,object,1,0.05,2
9,INFERRED_MENOPAUSAL_STATE,object,1,0.05,2
10,SEX,object,0,0.00,1
11,INTCLUST,object,1,0.05,11
12,AGE_AT_DIAGNOSIS,float64,0,0.00,1624
13,OS_MONTHS,float64,0,0.00,1743
14,OS_STATUS,object,0,0.00,2
15,CLAUDIN_SUBTYPE,object,1,0.05,7
16,THREEGENE,object,217,10.95,4
17,VITAL_STATUS,object,1,0.05,3
18,LATERALITY,object,111,5.60,2
19,RADIO_THERAPY,object,1,0.05,2
20,HISTOLOGICAL_SUBTYPE,object,44,2.22,8
21,BREAST_SURGERY,object,26,1.31,2
22,RFS_MONTHS,float64,0,0.00,1716
23,RFS_STATUS,object,1,0.05,2
24,SAMPLE_ID,object,0,0.00,1981
25,CANCER_TYPE,object,0,0.00,1
26,CANCER_TYPE_DETAILED,object,0,0.00,8
27,ER_STATUS,object,0,0.00,2
28,HER2_STATUS,object,1,0.05,2
29,GRADE,float64,88,4.44,3
30,ONCOTREE_CODE,object,0,0.00,8
31,PR_STATUS,object,1,0.05,2
32,SAMPLE_TYPE,object,0,0.00,1
33,TUMOR_SIZE,float64,26,1.31,112
34,TUMOR_STAGE,float64,515,26.00,5
35,TMB_NONSYNONYMOUS,float64,0,0.00,31
36,EVENT,int64,0,0.00,2

In [21]:

clinical_features = [
    "AGE_AT_DIAGNOSIS",
    "TUMOR_SIZE",
    "GRADE",
    "LYMPH_NODES_EXAMINED_POSITIVE",
    "ER_STATUS",
    "PR_STATUS",
    "HER2_STATUS"
]

clinical_features_with_stage = (
    clinical_features + ["TUMOR_STAGE"]
)

outcome_columns = [
    "OS_MONTHS",
    "EVENT"
]

X_train = train_df[clinical_features].copy()

X_test = test_df[clinical_features].copy()

X_train_stage = train_df[
    clinical_features_with_stage
].copy()

X_test_stage = test_df[
    clinical_features_with_stage
].copy()

y_train = train_df[outcome_columns].copy()

y_test = test_df[outcome_columns].copy()

print("Training features:", X_train.shape)

print("Test features:", X_test.shape)

print("Training outcomes:", y_train.shape)

print("Test outcomes:", y_test.shape)

Training features: (1584, 7)
Test features: (397, 7)
Training outcomes: (1584, 2)
Test outcomes: (397, 2)

In [23]:

missing_summary = pd.DataFrame({
    "Missing_Count": X_train_stage.isna().sum(),
    "Missing_Percentage": (
        X_train_stage.isna().mean() * 100
    )
})

display(
    missing_summary.sort_values(
        by="Missing_Percentage",
        ascending=False
    ).round(2)
)

                               Missing_Count  Missing_Percentage
TUMOR_STAGE                              420               26.52
GRADE                                     72                4.55
LYMPH_NODES_EXAMINED_POSITIVE             61                3.85
TUMOR_SIZE                                21                1.33
PR_STATUS                                  1                0.06
HER2_STATUS                                1                0.06
AGE_AT_DIAGNOSIS                           0                0.00
ER_STATUS                                  0                0.00

In [25]:

categorical_features = [
    "ER_STATUS",
    "PR_STATUS",
    "HER2_STATUS",
    "GRADE",
    "TUMOR_STAGE"
]

for column in categorical_features:
    print("\n", column)

    print(
        X_train_stage[column].value_counts(
            dropna=False
        )
    )

 ER_STATUS
ER_STATUS
Positive    1205
Negative     379
Name: count, dtype: int64

 PR_STATUS
PR_STATUS
Positive    840
Negative    743
NaN           1
Name: count, dtype: int64

 HER2_STATUS
HER2_STATUS
Negative    1391
Positive     192
NaN            1
Name: count, dtype: int64

 GRADE
GRADE
3.0    754
2.0    629
1.0    129
NaN     72
Name: count, dtype: int64

 TUMOR_STAGE
TUMOR_STAGE
2.0    662
NaN    420
1.0    391
3.0     94
0.0     11
4.0      6
Name: count, dtype: int64

In [27]:

numerical_features = [
    "AGE_AT_DIAGNOSIS",
    "TUMOR_SIZE",
    "LYMPH_NODES_EXAMINED_POSITIVE"
]

display(
    X_train[numerical_features].describe().T
)

,count,mean,std,min,25%,50%,75%,max
AGE_AT_DIAGNOSIS,1584.0,61.108952,12.911335,21.93,51.4425,61.945,70.6425,96.29
TUMOR_SIZE,1563.0,26.442969,15.911130,1.00,18.0000,23.000,30.0000,182.00
LYMPH_NODES_EXAMINED_POSITIVE,1523.0,1.952068,3.883614,0.00,0.0000,0.000,2.0000,45.00

In [29]:

followup_summary = pd.DataFrame({
    "Training": y_train["OS_MONTHS"].describe(),
    "Test": y_test["OS_MONTHS"].describe()
})

display(followup_summary.round(2))

print(
    "\nZero-duration patients in training:",
    (y_train["OS_MONTHS"] == 0).sum()
)

print(
    "Zero-duration patients in test:",
    (y_test["OS_MONTHS"] == 0).sum()
)

       Training    Test
count   1584.00  397.00
mean     125.04  126.07
std       76.03   76.51
min        0.00    1.27
25%       60.09   61.90
50%      116.97  114.33
75%      185.21  184.70
max      355.20  335.73

Zero-duration patients in training: 1
Zero-duration patients in test: 0

In [31]:

valid_train_mask = (
    y_train["OS_MONTHS"].notna()
    & y_train["EVENT"].notna()
    & (y_train["OS_MONTHS"] > 0)
)

X_train_model = X_train.loc[
    valid_train_mask
].copy()

y_train_model = y_train.loc[
    valid_train_mask
].copy()

print(
    "Original training patients:",
    len(X_train)
)

print(
    "Patients available for model fitting:",
    len(X_train_model)
)

print(
    "Excluded zero-duration patients:",
    (~valid_train_mask).sum()
)

print(
    "Test patients:",
    len(X_test)
)

Original training patients: 1584
Patients available for model fitting: 1583
Excluded zero-duration patients: 1
Test patients: 397

In [33]:

numeric_features = [
    "AGE_AT_DIAGNOSIS",
    "TUMOR_SIZE",
    "LYMPH_NODES_EXAMINED_POSITIVE"
]

categorical_features = [
    "GRADE",
    "ER_STATUS",
    "PR_STATUS",
    "HER2_STATUS"
]

print("Numerical features:", numeric_features)

print("Categorical features:", categorical_features)

assert set(
    numeric_features + categorical_features
) == set(X_train_model.columns)

Numerical features: ['AGE_AT_DIAGNOSIS', 'TUMOR_SIZE', 'LYMPH_NODES_EXAMINED_POSITIVE']
Categorical features: ['GRADE', 'ER_STATUS', 'PR_STATUS', 'HER2_STATUS']

In [37]:

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        )
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            )
        )
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            numeric_pipeline,
            numeric_features
        ),
        (
            "categorical",
            categorical_pipeline,
            categorical_features
        )
    ],
    remainder="drop",
    verbose_feature_names_out=False
)

print("Preprocessing pipeline created successfully!")

Preprocessing pipeline created successfully!

In [39]:

X_train_processed_array = (
    preprocessor.fit_transform(X_train_model)
)

X_test_processed_array = (
    preprocessor.transform(X_test)
)

processed_feature_names = (
    preprocessor.get_feature_names_out()
)

X_train_processed = pd.DataFrame(
    X_train_processed_array,
    columns=processed_feature_names,
    index=X_train_model.index
)

X_test_processed = pd.DataFrame(
    X_test_processed_array,
    columns=processed_feature_names,
    index=X_test.index
)

print(
    "Processed training shape:",
    X_train_processed.shape
)

print(
    "Processed test shape:",
    X_test_processed.shape
)

display(X_train_processed.head())

Processed training shape: (1583, 12)
Processed test shape: (397, 12)

,AGE_AT_DIAGNOSIS,TUMOR_SIZE,LYMPH_NODES_EXAMINED_POSITIVE,GRADE_1.0,GRADE_2.0,GRADE_3.0,ER_STATUS_Negative,ER_STATUS_Positive,PR_STATUS_Negative,PR_STATUS_Positive,HER2_STATUS_Negative,HER2_STATUS_Positive
1821,50.42,26.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
351,39.53,16.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
669,54.64,22.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
830,73.20,30.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
765,45.74,20.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [41]:

print(
    "Training missing values:",
    X_train_processed.isna().sum().sum()
)

print(
    "Test missing values:",
    X_test_processed.isna().sum().sum()
)

print(
    "Same feature columns:",
    X_train_processed.columns.equals(
        X_test_processed.columns
    )
)

print(
    "Training outcome alignment:",
    X_train_processed.index.equals(
        y_train_model.index
    )
)

print(
    "Test outcome alignment:",
    X_test_processed.index.equals(
        y_test.index
    )
)

assert X_train_processed.isna().sum().sum() == 0

assert X_test_processed.isna().sum().sum() == 0

assert X_train_processed.columns.equals(
    X_test_processed.columns
)

assert X_train_processed.index.equals(
    y_train_model.index
)

assert X_test_processed.index.equals(
    y_test.index
)

print("Preprocessing checks passed!")

Training missing values: 0
Test missing values: 0
Same feature columns: True
Training outcome alignment: True
Test outcome alignment: True
Preprocessing checks passed!

In [43]:

import joblib

PREPARED_DIR = PROJECT_DIR / "prepared_data"

PREPARED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

X_train_processed.to_csv(
    PREPARED_DIR / "X_train_processed.csv",
    index=False
)

X_test_processed.to_csv(
    PREPARED_DIR / "X_test_processed.csv",
    index=False
)

y_train_model.to_csv(
    PREPARED_DIR / "y_train.csv",
    index=False
)

y_test.to_csv(
    PREPARED_DIR / "y_test.csv",
    index=False
)

joblib.dump(
    preprocessor,
    PREPARED_DIR / "clinical_preprocessor.joblib"
)

print("Prepared datasets and preprocessor saved successfully!")

Prepared datasets and preprocessor saved successfully!